name: Terraform Workflow

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      example_input:
        description: 'An example input'
        required: true
        default: 'default value'

jobs:
  apply:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run Terraform
        run: |
          echo "Running Terraform with input: ${{ github.event.inputs.example_input }}"
