name: Terraform Workflow

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment prefix where we want the CB node to be restarted'
        type: choice
        options:
          - 'd'
          - 'q'
          - 's'
          - 'p'
         required: true
      example_input:
        description: 'An example input'
        required: true
        default: 'default value'

jobs:
  apply:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run Terraform
        run: |
          echo "Running Terraform with input: ${{ github.event.inputs.example_input }}"
          echo "Selected environment: ${{ github.event.inputs.environment }}"
