name: My Simple Action

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      example_input:
        description: 'An example input'
        required: true
        default: 'default value'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run a simple script
        run: echo "Hello, World! This action ran on push to main with input: ${{ github.event.inputs.example_input }}"
